#!/bin/sh

#
# Basic install of zopen
#

WORKDIR="$1"
INCLUDEDIR="$2"
zopen_tool_binary=$(type zopen | cut -d' ' -f3)
zopen_tool_directory=$( dirname "${zopen_tool_binary}" )

# include helper script
# shellcheck disable=SC1091
. "${INCLUDEDIR}/common.sh"

install_dummy_env

zopen list --installed

# The list of (small) packages to use as tests - if these work, then
# bigger packages should also
installPkgs="xz which bzip2 wget"

doing "Testing functionality of which" 
whichWhich=$(which which)
if [ ! "${whichWhich}" = "${zopenenv}/usr/local/bin/which" ]; then
  fail "Wrong which was used: expected: '${zopenenv}/usr/local/bin/which'; actual: '${whichWhich}'"
fi
did "Tested"

doing "Configuring the temporary directory for local pax files to install"
tstpkgcache="${zopenenv}/tstpkgcache"
[ -e "${tstpkgcache}" ] && rm -rf "${tstpkgcache}"
mkdir -p "${tstpkgcache}" || fail "Could not create directory '${tstpkgcache}'"
oldPwd="$PWD"
cd "${tstpkgcache}" || fail "Could not change to directory '${tstpkgcache}'"
did "Configured"

doing "Downloading packages using zopen itself"
if ! zopen install --yes --download-only ${installPkgs}; then
  fail "Error installing test packages"
fi
did "Downloaded"

cd "${oldPwd}" || fail "Could not return to directory '${oldPwd}'"

doing -n "Removing installed test packages"
zopen remove --yes --purge xz bzip2 wget
did "Removed test packages"

doing -n "Configuring variables for use as filenames"
# Automagically populate envvars that are the package names with the appropriate
# file, noting that this allows for dynamic names, not hardcoding specific versions
for file in "$tstpkgcache"/*.Z; do
  [ -n "${file}" ] || continue
  basefile=$(basename "$file")
  # Extract the prefix (everything before the last hyphen), in uppercase with no - or _
  prefix=$(echo "$basefile" | sed 's/\(.*\)-[^-]*$/\1/' | tr 'a-z' 'A-Z' | sed 's/[-_]//g')
  # Assign the filename to the generated variable name
  eval "$prefix=\"$file\""
  echo "$prefix=$file"
done
echo "WORKDIR: ${WORKDIR}"
echo "zopen_tool_binary: ${zopen_tool_binary}"
echo "zopen_tool_directory: ${zopen_tool_directory}"
did "Configured variables for use as filenames"

zopen_test_begin "Testing install from current directory"
cd "${tstpkgcache}" || fail "Cannot change to test cache directory"
cmd="zopen install ${XZ} -y"
doing "Testing command: ${cmd}"
if ! $cmd; then
  fail "Test to install package '${XZ}' failed"
fi
did

cd - || fail "Could not return to previous directory?!?"

doing "Checking version of xz currently in use"
whichxz=$(which xz)
if [ ! "${whichxz}" = "${zopenenv}/usr/local/bin/xz" ]; then
  fail "xz was not found at the expected location: expected: '${zopenenv}/usr/local/bin/xz'; actual: '${whichxz}'"
fi
did
zopen_test_end

zopen_test_begin "Testing install from relative directory"
oldpwd="$PWD"
cd "${tstpkgcache}/.." || fail "Cannot change to test cache directory"
cmd="zopen install "$(basename "${tstpkgcache}")/$(basename "${BZIP2}")" -y"
doing -n "Test command: ${cmd}"
if ! $cmd; then
  fail "Relative Test to install package '${BZIP2}' failed"
fi
did "Completed ${cmd}"

cd "${oldpwd}" || fail "Could not return to previous directory '${oldpwd}'?!?"
doing "Testing version of bzip2 in use"
whichbzip2=$(which bzip2)
if [ ! "${whichbzip2}" = "${zopenenv}/usr/local/bin/bzip2" ]; then
  fail "bzip2 was not found at the expected location: expected: '${zopenenv}/usr/local/bin/bzip2'; actual: '${whichbzip2}'"
fi
did
zopen_test_end

zopen_test_begin "Testing install from absolute directory"
cmd="zopen install ${tstpkgcache}/$(basename "${WGET}") --yes"
doing -n "Test command: ${cmd}"
if ! $cmd; then
  fail "Absolute Test to install package '${WGET}' failed"
fi
did "Command executed as expected: ${cmd}"

whichwget=$(which wget)
if [ ! "${whichwget}" = "${zopenenv}/usr/local/bin/wget" ]; then
  fail "wget was not found at the expected location: expected: '${zopenenv}/usr/local/bin/wget'; actual: '${whichwget}'"
fi
zopen_test_end

set -x
zopen_test_begin "Testing install caveat display"
caveatOutput="${zopenenv}/tmp/caveatoutput.txt"
cmd="zopen install prompters --yes"

doing -n "Test output from command: ${cmd}"
if !  $cmd > "${caveatOutput}" 2>&1; then
  fail "Installation of prompters package failed"
fi
did
if ! grep -q "Please make sure to run mandb to create or update the manual page index" "${caveatOutput}"; then
  fail "Could not locate Caveat output from prompters"
fi
zopen_test_end

zopen_test_begin "Testing database generation"
packageDB="${zopenenv}/var/lib/zopen/packageDB.json"
if [ -e "${packageDB}" ]; then
  doing "Removing existing package database at: %s" "${packageDB}"
  rm "${packageDB}"
  did
fi
doing "Getting installed package list (to re-generate database)"
if ! listout=$(zopen list --installed 2>&1); then
  fail "List package command unexpectedly failed.\n${listout}"
fi
did
doing "Checking for WARNING message"
if ! echo "${listout}" | grep -q "WARNING: No package database found."; then
  fail "No message indicating package database was being updated.\n${listout}"
fi
did

if [ ! -e "${packageDB}" ]; then
  fail "Install package database not found/created"
fi
zopen_test_end

zopen_test_begin "Testing list of installed packages"
installedPkgs=$(echo "$installPkgs prompters" | tr ' ' '\n')
doing -n "Generating list of installed packages"
if ! listout=$(zopen list --installed); then
  fail "Could not obtain list of installed packages.\n${listout}"
fi

commTmpdir="${WORKDIR}/tmp/comm"
[ -e "${commTmpdir}" ] && rm -rf "${commTmpdir}"
mkdir -p "${commTmpdir}"
# shellcheck disable=SC3037 # Works on z/OS
echo -e "$installedPkgs" | sort > "${commTmpdir}/ip.txt"
printf "Wanted packages (sorted):\n%s\n" "${installedPkgs}"
# shellcheck disable=SC3037 # Works on z/OS
echo -e "$listout" | sort > "${commTmpdir}/lo.txt"
printf "Installed packages (sorted):\n%s\n" "${listout}"
doing "Comparing package lists"
if ! commOut=$(comm -3 "${commTmpdir}/ip.txt" "${commTmpdir}/lo.txt"); then
  fail "Error trying to compare input/output in files '${commTmpdir}/ip.txt' '${commTmpdir}/lo.txt'.\n${commOut}"
fi
did
doing "Cleaning temporary files"
[ -e  "${commTmpdir}/ip.txt" ] && rm "${commTmpdir}/ip.txt"
[ -e "${commTmpdir}/lo.txt" ] && rm "${commTmpdir}/lo.txt"
did
zopen_test_end

zopen_test_begin "Testing removal of dependent package"
cmd="zopen remove groff"
doing -n "Attempting to remove groff [passing 'n']"
if groffRemove=$(echo "n" | $cmd); then
  fail "Removal of groff package succeeded; should fail as a dependent of prompters"
fi
did "Groff removal failed as expected"

doing "Checking for WARNING message from attemped groff removal"
if ! echo "${groffRemove}" | grep -q "WARNING: Removing groff could result in broken packages"; then
  fail "Removal of dependent package message not found"
fi
did

cmd="zopen remove --yes groff"
doing -n "Forcing removal of groff using command: $cmd"
if ! groffRemove=$($cmd); then
  fail "Removal of groff package failed; should uninstall given the --yes flag"
fi
did "Removal completed as expected"
zopen_test_end

# Cleanup
[ -e "${zopenenv}" ] && echo "Clearing existing work env" && rm -rf "${zopenenv}"
exit 0

