#!/bin/sh

#
# Basic 'zopen help' check for all tools in 'bin'
#
set -e # hard failure if any commands fail
WORKDIR="$1"
zopen_tool_binary=`whence zopen`
zopen_tool_directory=$( dirname ${zopen_tool_binary} )

tools=$( cd "${zopen_tool_directory}" && echo zopen zopen-* )
for zopen_tool in $tools; do
  "${zopen_tool}" --help >/dev/null 2>&1
  if [ $? -gt 0 ]; then
    echo "${zopen_tool} has not implemented --version option" >&2
    exit 4
  fi
done

exit 0

