#!/bin/sh

#
# Basic 'zopen install' check
#

WORKDIR="$1"
INCLUDEDIR="$2"
zopen_tool_binary=`whence zopen`
zopen_tool_directory=$( dirname ${zopen_tool_binary} )

# Display banner
${INCLUDEDIR}/banner.sh "tests/check_install"


echo "Tests starting ..."
echo "-- Current Settings: ---"
echo "WORKDIR: ${WORKDIR}"
echo "zopen_tool_binary: ${zopen_tool_binary}"
echo "zopen_tool_directory: ${zopen_tool_directory}"

if ! zopen install zotsample -y; then
    echo "Test of simple install failed."
    return 4
fi

result=$(zopen install zotsampleport)
expected_result="Usage error: please install using base name without port suffix.
  try: zopen install zotsample"
if [[ "${result}" != "${expected_result}" ]]; then
    echo "Test of identifying port suffix failed."
    return 4
fi

#TODO: Add test to check for specific version to install
# How to specify with --select

#TODO: Add test to check for specific tag to install
# How to specify with --select

exit 0





